<?php

$Meditations = new Chunk("meditations","Marcus Aurelius Meditations","https://www.goodreads.com/author/quotes/17212.Marcus_Aurelius");
$Meditations->included = false; // don't show this by default

$category = "Stoicism";
/*
$Meditations->addNugget($category, "You have power over your mind - not outside events. Realize this, and you will find strength.");
$Meditations->addNugget($category, "Dwell on the beauty of life. Watch the stars, and see yourself running with them.");
$Meditations->addNugget($category, "The happiness of your life depends upon the quality of your thoughts.");
$Meditations->addNugget($category, "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.");
$Meditations->addNugget($category, "Waste no more time arguing about what a good man should be. Be one.");
$Meditations->addNugget($category, "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.");
$Meditations->addNugget($category, "When you arise in the morning think of what a privilege it is to be alive, to think, to enjoy, to love ...");
$Meditations->addNugget($category, "The best revenge is to be unlike him who performed the injury.");
$Meditations->addNugget($category, "Accept the things to which fate binds you, and love the people with whom fate brings you together,but do so with all your heart.");
$Meditations->addNugget($category, "The soul becomes dyed with the colour of its thoughts.");
$Meditations->addNugget($category, "It is not death that a man should fear, but he should fear never beginning to live.");
$Meditations->addNugget($category, "Our life is what our thoughts make it.");
$Meditations->addNugget($category, "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.");
$Meditations->addNugget($category, "If someone is able to show me that what I think or do is not right, I will happily change, for I seek the truth, by which no one was ever truly harmed. It is the person who continues in his self-deception and ignorance who is harmed.");
$Meditations->addNugget($category, "If it is not right do not do it; if it is not true do not say it.");
$Meditations->addNugget($category, "I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinion of himself than on the opinion of others.");
$Meditations->addNugget($category, "Whenever you are about to find fault with someone, ask yourself the following question: What fault of mine most nearly resembles the one I am about to criticize?");
$Meditations->addNugget($category, "Very little is needed to make a happy life; it is all within yourself in your way of thinking.");
$Meditations->addNugget($category, "The object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.");
$Meditations->addNugget($category, "The best revenge is not to be like your enemy.");
$Meditations->addNugget($category, "Reject your sense of injury and the injury itself disappears.");
$Meditations->addNugget($category, "When another blames you or hates you, or people voice similar criticisms, go to their souls, penetrate inside and see what sort of people they are. You will realize that there is no need to be racked with anxiety that they should hold any particular opinion about you.");
$Meditations->addNugget($category, "The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are.");
$Meditations->addNugget($category, "How much more grievous are the consequences of anger than the causes of it.");
$Meditations->addNugget($category, "Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.");
$Meditations->addNugget($category, "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.");
$Meditations->addNugget($category, "Here is a rule to remember in future, when anything tempts you to feel bitter: not \"This is misfortune,\" but \"To bear this worthily is good fortune.\"");
$Meditations->addNugget($category, "Live a good life. If there are gods and they are just, then they will not care how devout you have been, but will welcome you based on the virtues you have lived by. If there are gods, but unjust, then you should not want to worship them. If there are no gods, then you will be gone, but will have lived a noble life that will live on in the memories of your loved ones.");
$Meditations->addNugget($category, "How much time he gains who does not look to see what his neighbour says or does or thinks, but only at what he does himself, to make it just and holy.");
$Meditations->addNugget($category, "Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness – all of them due to the offenders' ignorance of what is good or evil.");
$Meditations->addNugget($category, "You are a little soul carrying about a corpse, as Epictetus used to say.");
$Meditations->addNugget($category, "Do every act of your life as though it were the very last act of your life.");
$Meditations->addNugget($category, "Think of yourself as dead. You have lived your life. Now, take what's left and live it properly. What doesn't transmit light creates its own darkness.");
$Meditations->addNugget($category, "What we do now echoes in eternity.");
$Meditations->addNugget($category, "You always own the option of having no opinion. There is never any need to get worked up or to trouble your soul about things you can't control. These things are not asking to be judged by you. Leave them alone.");
$Meditations->addNugget($category, "Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess, and then thankfully remember how you would crave for them if they were not yours.");
$Meditations->addNugget($category, "Look back over the past, with its changing empires that rose and fell, and you can foresee the future too.");
$Meditations->addNugget($category, "For it is in your power to retire into yourself whenever you choose.");
$Meditations->addNugget($category, "Perfection of character is this: to live each day as if it were your last, without frenzy, without apathy, without pretence.");
*/
$Meditations->addNugget($category, "The universe is change; our life is what our thoughts make it.");
/*
$Meditations->addNugget($category, "Remember that very little is needed to make a happy life.");
$Meditations->addNugget($category, "Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.");
$Meditations->addNugget($category, "A man's worth is no greater than the worth of his ambitions.");
$Meditations->addNugget($category, "The impediment to action advances action. What stands in the way becomes the way.");
$Meditations->addNugget($category, "Nothing happens to anybody which he is not fitted by nature to bear.");
$Meditations->addNugget($category, "Receive without conceit, release without struggle.");
$Meditations->addNugget($category, "Don't go on discussing what a good person should be. Just be one.");
$Meditations->addNugget($category, "It is in your power to withdraw yourself whenever you desire. Perfect tranquility within consists in the good ordering of the mind, the realm of your own.");
$Meditations->addNugget($category, "Life is neither good or evil, but only a place for good and evil.");
$Meditations->addNugget($category, "How ridiculous and how strange to be surprised at anything which happens in life");
$Meditations->addNugget($category, "Your days are numbered. Use them to throw open the windows of your soul to the sun. If you do not, the sun will soon set, and you with it.");
$Meditations->addNugget($category, "Whatever anyone does or says, I must be emerald and keep my colour.");
$Meditations->addNugget($category, "If any man despises me, that is his problem. My only concern is not doing or saying anything deserving of contempt.");
$Meditations->addNugget($category, "Humans have come into being for the sake of each other, so either teach them, or learn to bear them.");
$Meditations->addNugget($category, "If someone can prove me wrong and show me my mistake in any thought or action, I shall gladly change. I seek the truth, which never harmed anyone: the harm is to persist in one's own self-deception and ignorance.");
$Meditations->addNugget($category, "Do what you will. Even if you tear yourself apart, most people will continue doing the same things.");
$Meditations->addNugget($category, "Though you break your heart, men will go on as before.");
$Meditations->addNugget($category, "Do not act as if you had ten thousand years to throw away. Death stands at your elbow. Be good for something while you live and it is in your power.");
$Meditations->addNugget($category, "The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.");
$Meditations->addNugget($category, "Accept whatever comes to you woven in the pattern of your destiny, for what could more aptly fit your needs?");
$Meditations->addNugget($category, "Regain your senses, call yourself back, and once again wake up. Now that you realize that only dreams were troubling you, view this 'reality' as you view your dreams.");
$Meditations->addNugget($category, "Whoever does wrong, wrongs himself; whoever does injustice, does it to himself, making himself evil.");
$Meditations->addNugget($category, "A person's worth is measured by the worth of what he values.");
$Meditations->addNugget($category, "Observe always that everything is the result of change, and get used to thinking that there is nothing Nature loves so well as to change existing forms and make new ones like them.");
$Meditations->addNugget($category, "If you are pained by external things, it is not they that disturb you, but your own judgement of them. And it is in your power to wipe out that judgement now.");
$Meditations->addNugget($category, "The memory of everything is very soon overwhelmed in time.");
$Meditations->addNugget($category, "Nowhere can man find a quieter or more untroubled retreat than in his own soul.");
$Meditations->addNugget($category, "The things you think about determine the quality of your mind.");
$Meditations->addNugget($category, "Because a thing seems difficult for you, do not think it impossible for anyone to accomplish.");
$Meditations->addNugget($category, "It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own.");
$Meditations->addNugget($category, "The happiness of those who want to be popular depends on others; the happiness of those who seek pleasure fluctuates with moods outside their control; but the happiness of the wise grows out of their own free acts.");
$Meditations->addNugget($category, "Confine yourself to the present.");
$Meditations->addNugget($category, "Pass then through this little space of time conformably to nature, and end thy journey in content, just as an olive falls off when it is ripe, blessing nature who produced it, and thanking the tree on which it grew.");
$Meditations->addNugget($category, "Misfortune nobly born is good fortune.");
$Meditations->addNugget($category, "Dig within. Within is the wellspring of Good; and it is always ready to bubble up, if you just dig.");
$Meditations->addNugget($category, "The art of living is more like wrestling than dancing, in so far as it stands ready against the accidental and the unforeseen, and is not apt to fall.");
$Meditations->addNugget($category, "Be like the cliff against which the waves continually break; but it stands firm and tames the fury of the water around it.");
$Meditations->addNugget($category, "Take full account of what Excellencies you possess, and in gratitude remember how you would hanker after them, if you had them not.");
$Meditations->addNugget($category, "That which is really beautiful has no need of anything; not more than law, not more than truth, not more than benevolence or modesty.");
$Meditations->addNugget($category, "No one can lose either the past or the future - how could anyone be deprived of what he does not possess? ... It is only the present moment of which either stands to be deprived: and if this is all he has, he cannot lose what he does not have.");
$Meditations->addNugget($category, "Choose not to be harmed-and you won't feel harmed. Don't feel harmed-and you haven't been.");
$Meditations->addNugget($category, "A man must stand erect, not be kept erect by others.");
$Meditations->addNugget($category, "Every living organism is fulfilled when it follows the right path for its own nature.");
*/
$Wisdom->addChunk($Meditations);
