<?php
$MaxMarmer = new Chunk("patterns","Principles, Patterns and Values by Max Marmer","https://www.maxmarmer.com/blog/principles-patterns-values/");

$category = "Principles, Patterns and Values";
$MaxMarmer->addNugget($category, "Do things like evolution. Throw stuff at the wall and see what sticks. Take the best stuff. Iterate.");
$MaxMarmer->addNugget($category, "Change is accelerating. Our intuition operates linearly and has trouble perceiving exponential transformations.");
$MaxMarmer->addNugget($category, "You do not truly have free will until you transcend your ego.");
$MaxMarmer->addNugget($category, "Surround yourself with amazing people. You will become who you surround yourself with.");
$MaxMarmer->addNugget($category, "The only thing constant is change. Embrace it.");
$MaxMarmer->addNugget($category, "Feedback is a powerful, life shaping force. Look to get more of it and incorporate into designs, projects and life.");
$MaxMarmer->addNugget($category, "You can't be good at everything. Don't feel bad about it.");
$MaxMarmer->addNugget($category, "Burning desire is the energy of achievement.");
$MaxMarmer->addNugget($category, "Be proactive about what you want. Laziness and apathy are diseases.");
$MaxMarmer->addNugget($category, "Don't settle.");
$MaxMarmer->addNugget($category, "Create a compelling vision of where you want to go and who you want to be.");
$MaxMarmer->addNugget($category, "Align your emotional system to take you there.");
$MaxMarmer->addNugget($category, "Think big. Learn from failure. Never give up. Ever.");
$MaxMarmer->addNugget($category, "Think Long-term.");
$MaxMarmer->addNugget($category, "Transparency wins in the long run.");
$MaxMarmer->addNugget($category, "Focus on the right things. Products not Byproducts. Actionable Metrics not Vanity Metrics.");
$MaxMarmer->addNugget($category, "Life progresses in a series of phases. Understand what phase you're in and live it. Don't mix phases. Have Patience. Work Diligently. You will get everything you need in due time.");
$MaxMarmer->addNugget($category, "Strive to reduce \"what you don't know you don't know\" to \"you know you don't know\".");
$MaxMarmer->addNugget($category, "Art and science have similar aims. To enhance the way we perceive the world.");
$MaxMarmer->addNugget($category, "Underneath every art is an undiscovered science.");
$MaxMarmer->addNugget($category, "Balance Analysis and Synthesis. Top down and bottom up.");
$MaxMarmer->addNugget($category, "The Universe is one big, interconnected system. Almost everything is a nested set of systems, made up of other interconnected systems. A hierarchy. A holarchy.");
$MaxMarmer->addNugget($category, "Reality is a complex system, navigating complex systems requires systems theory.");
$MaxMarmer->addNugget($category, "Technology and culture are interdependent and coevolve.");
$MaxMarmer->addNugget($category, "Seed. Organism. Environment.");
$MaxMarmer->addNugget($category, "Batch work. The mind isn't that good at gear shifting.");
$MaxMarmer->addNugget($category, "Complex systems don't start out complex. They evolve from simplicity to complexity through iteration.");
$MaxMarmer->addNugget($category, "\"Equality of Opportunity\" rather than \"Equality of Outcomes\". The homeostasis of many complex systems are a power law distribution.");
$MaxMarmer->addNugget($category, "You are a creature of habit. Define your habits rather than let them define you.");
$MaxMarmer->addNugget($category, "You have to know what you want.");
$MaxMarmer->addNugget($category, "Strengthen your good feelings through the positive abstract, temper your bad feelings through the negative concrete.");
$MaxMarmer->addNugget($category, "Understanding requires looking at the system from the right perspective. Sometimes understanding requires looking at emergent properties. Sometimes it requires breaking pieces apart. Intelligence is knowing which.");
$MaxMarmer->addNugget($category, "Intelligence and wisdom increase rapidly when you can become aware of your mind's model of reality. Consciously test assumptions and improve your model.");
$MaxMarmer->addNugget($category, "Control your thoughts. Choose where you want them to wander. And don't ever let them wander down dark streams when you are tired. Darkness should be confronted, but only when you have the energy to overcome it. Rest. Train. And go to battle strong.");
$MaxMarmer->addNugget($category, "How much you accomplish is proportional to how much energy you have, not how much time.");
$MaxMarmer->addNugget($category, "Strive for emotional flexibility and control.");
$MaxMarmer->addNugget($category, "Ask questions at a rapid rate. Don't be afraid of looking stupid.");
$MaxMarmer->addNugget($category, "Don't tie your identity to your present knowledge. Tie your identity to who you can become.");
$MaxMarmer->addNugget($category, "Your mind is an evolving associative network of connections. Whenever you read or talk to someone you are programming your mind. Be mindful of this. Program your mind to think the right way. The mind accepts without caring too much about what's true or false.");
$MaxMarmer->addNugget($category, "Most people will give you advice without understanding your situation.");
$MaxMarmer->addNugget($category, "There are no shortcuts. Anyone who is amazing at anything has put a lot of time into it. Excellence is the result of time and energy being invested in the right places.");
$MaxMarmer->addNugget($category, "Mastering the self is the ultimate freedom.");
$MaxMarmer->addNugget($category, "If you want to grow quickly you must separate yourself, your identity, your ego from your ideas, emotions and thoughts.");
$MaxMarmer->addNugget($category, "Read a lot about what you want to do, try and find people you can model. Read their writings, biographies, then go out and meet those people.");
$MaxMarmer->addNugget($category, "Delayed gratification is essential for long term progress.");
$MaxMarmer->addNugget($category, "Take time to reflect. Especially about yourself. Journaling is a very effective way to do this. Journaling has vastly accelerated my learning curve, my acquisition of wisdom.");
$MaxMarmer->addNugget($category, "Reflection allows for the extraction of patterns with very limited experience. Experience takes many more data points to develop the same intuition of the same phenomenon.");
$MaxMarmer->addNugget($category, "Rarely should you feel overwhelmed in life. It's the result of taking on too much, unrealistic expectations, or continual slacking. Prioritize and pace yourself.");
$MaxMarmer->addNugget($category, "Your best relationship should be with yourself.");
$MaxMarmer->addNugget($category, "Write everything down. You can't hold it all in your mind. It takes away \"RAM\" to focus on the present.");
$MaxMarmer->addNugget($category, "The fundament of relationships is mutual growth.");
$MaxMarmer->addNugget($category, "Personal growth is more about stripping away limiting beliefs, insecurities, bad habits, resentments and traumas than adding anything to yourself. Your goal is to become free to expand.");
$MaxMarmer->addNugget($category, "Life is simple if you focus on what matters most and don't get caught chasing byproducts and shiny objects.");
$MaxMarmer->addNugget($category, "Think Big. Start Small. Scale fast.");
$MaxMarmer->addNugget($category, "Understand what's a byproduct and what the actual end goal you should focus on. Don't focus on the byproducts like money, success, fame or love. These are rewards for living life correctly.");
$MaxMarmer->addNugget($category, "Find the right balance of bottom up and top down. The ratio is often 95/5, respectively.");
$MaxMarmer->addNugget($category, "Problems often are embedded in systems. Systems have desired outcomes and equilibrium points. If you want to fix a problem that's embedded in a system, and you don't change the system, your change will be temporary and your effort will be in vain. You can win a few battles but you can never win the war.");
$MaxMarmer->addNugget($category, "There's no such thing as an overnight success. Success is years in the making and eventually a tipping point is reached.");
$MaxMarmer->addNugget($category, "Whenever you're thinking about the future identify the hypothesis, assumptions and trends. What are you taking a bet on?");
$MaxMarmer->addNugget($category, "Learn something from every situation. Never stop learning.");
$MaxMarmer->addNugget($category, "Your daily life is also a system. Build systems and habits with your energy and will power each day. Make your life scalable.");
$MaxMarmer->addNugget($category, "Most people are looking to escape themselves rather than transform themselves.");
$MaxMarmer->addNugget($category, "Our greatest limitation is the size of our dreams.");
$MaxMarmer->addNugget($category, "Self-similarity is everywhere in the universe. You just have to look.");
$MaxMarmer->addNugget($category, "One of the biggest shifts in worldview that is so crucial, that most people will never make, is that we are our pattern not our matter.");
$MaxMarmer->addNugget($category, "Understand the lines of intrinsic value and the line of hype that oscillates over it, sometimes with great amplitude. This is why there are boom cycles and bust cycles but the world keeps moving forward.");
$MaxMarmer->addNugget($category, "Distinguish perceived value from intrinsic value.");
$MaxMarmer->addNugget($category, "Take actions towards your dreams everyday and they will become real. Reality cannot help but bend against an adapting, evolving persistent action.");
$MaxMarmer->addNugget($category, "When you relate to yourself make your visions of who you can become as grandiose as possible.");
$MaxMarmer->addNugget($category, "Relate to others with respect and humility.  If you can learn something from them, ask. If they can learn something from you, speak to them where they are.");
$MaxMarmer->addNugget($category, "As the wealth of the world rises, win-win situations are increasingly possible in all circumstances.");
$MaxMarmer->addNugget($category, "Having big visions for yourself does not mean you should be delusional. To make dreams a reality you must be extremely logical and honest about where you are now, and what the next steps for growth are. A journey of a thousand miles starts with a single step.");
$MaxMarmer->addNugget($category, "When times get tough keep putting one foot in front of the other. Just keep breathing.");
$MaxMarmer->addNugget($category, "Psychology (Developmental consciousness, biases and irrationality, will power, habits, \"us & them\", evolutionary psychology, emotional vs. logical decision-making, fear of loss is greater than potential gain, preferences vs attachment, Moving \"through time\" or \"in-time\", personality types, Dunbar number, what somebody means is frequently not what they say)","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Modeling (classifications, iterative improvement, tradeoff between precision and cost)","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Systems (Momentum, tendencies, incentives, partial truths that grow in completeness, layers & perspectives, concrete vs abstract, path dependency, fractal patterns, power laws, strong vs weak ties)","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Scientific Method","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Evolution and Development (convergent and divergent, centralization vs. decentralization, generative and decisive, punctuated equilibrium)","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Patternism (exponential vs. linear progress)","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Universal Values/Tendencies: Intelligence, Complexity, Evolution and Development, Diversity, Connectivity, Information, Evolvability","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Evolution now happens in the realm of the informational rather than the physical. Learning is the fundamental unit of progress for people, startups, and the universe.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Discovery, Validation, Efficiency, Scale, may be a universal design pattern.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "The job of our species, planet, maybe even universe is to discover, and spread our insight and creations as far and as wide as possible.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Humanity appears to be at the forefront of the universe's development but we will soon pass the baton as we more fully merge with our technology and become a new enhanced species.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Everything will become an information science. Progress often becomes exponential once sciences become information sciences.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Anything that gained widespread cultural adoption probably has some truth it.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "The universe contains both form and the formless. Bhuddism got only half of the equation right. It evolved in a time where the pace of change was to slow to perceive the inexorable march forward of the world of form.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Reality is not something to escape. It is our evolutionary duty to participate in the unfolding of the world of form.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Greater truth is found through increasing coherence and increasing correspondence.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Developmental systems have a direction. The universe is a developmental system.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Questions are worth more than answers.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Life appears to be an infinite game.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Confusion precedes deep understanding.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Build up a large library of mental models and abstract concepts.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Intelligence is the ability to grow an associate network of connections that is ordered into increasing degrees of abstraction.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "You will overestimate what you can accomplish in the short term and underestimate what you can accomplish in the long term.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "You can have a huge vision but if you're not hitting milestones on the way that increasing your momentum and resources, you probably aren't getting any closer to achieving it.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "No matter how far you've gone down the wrong road turn back.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Visions are often wrong. They must be tested against reality. Your childhood dreams are probably bad dreams to pursue.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Constantly update your beliefs with what you've learned.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Learn from the past and have a 21st century conversation about what we know.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Don't spend too much time thinking about the things you cannot change.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Don't become too attached to your patterns, models, principles and values. If they aren't changing, you probably aren't growing.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Nothing in life is 100% certain. Life is a game of probabilities. God does play dice.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Be as open with your ideas as possible. Ideas may be incubated in private, but once they have a foundation and an internal coherence, they will only grow if they are put out in the open and given the opportunity to evolve.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Energy in the universe is constant. But intelligence is increasing.  Maybe our purpose is to transform random bits into ordered bits.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "The mind often works by making conclusions and working backwards to discover a logical line of reasoning. Insight does not come by building up from premises.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Humans are not rational. But that doesn't mean we aren't predictable.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "We must work with the programs of the mind until we have the ability to rewrite them.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "There are thinkers who are afraid of being wrong and there are thinkers that want to push the boundary as far as they can. This requires making assumptions on top of assumptions.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Ego-transcendence emerges from the pursuit of self-awareness.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Systems must balance efficiency with resiliency.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Most people don't reflect. Not reflecting makes you emotionally, intellectually, and spiritually obese. Reflection is the metabolic process that turns experience into wisdom.","Problem Solving Perspectives:");
$MaxMarmer->addNugget($category, "Kaizen. Continuous learning. Continuous improvement. Never stop growing and you will never grow old.","Problem Solving Perspectives:");
$Wisdom->addChunk($MaxMarmer);