<?php

$Sayings = new Chunk("sayings","Confucius Quotes","https://www.quoteambition.com/confucius-quotes/");

$category = "Sayings";

$Sayings->addNugget($category, "The man who says he can, and the man who says he can not... Are both correct.");
$Sayings->addNugget($category, "Your life is what your thoughts make it.");
$Sayings->addNugget($category, "Real knowledge is to know the extent of one's ignorance.");
$Sayings->addNugget($category, "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.");
$Sayings->addNugget($category, "The journey with a thousand miles begins with one step.");
$Sayings->addNugget($category, "Choose a job you love, and you will never have to work a day in your life.");
$Sayings->addNugget($category, "You are what you think.");
$Sayings->addNugget($category, "Looking at small advantages prevents great affairs from being accomplished.");
$Sayings->addNugget($category, "All people are the same; only their habits differ.");
$Sayings->addNugget($category, "Learn advidly. Question it repeatedly. Analyze it carefully. Then put what you have learned into practice intelligently.");
$Sayings->addNugget($category, "We have two lives, and the second begins when we realize we only have one.");
$Sayings->addNugget($category, "If you are the smartest person in the room, then you are in the wrong room.");
$Sayings->addNugget($category, "Act with kindness but do not expect gratitude.");
$Sayings->addNugget($category, "Worry not that no one knows you; seek to be worth knowing.");
$Sayings->addNugget($category, "The man who moves a mountain begins by carrying away small stones.");
$Sayings->addNugget($category, "When it is obvious that the goals cannot be reached, don't adjust the goals, adjust the action steps.");
$Sayings->addNugget($category, "The essence of knowledge is, having it, to use it.");
$Sayings->addNugget($category, "One joy dispels a hundred cares.");
$Sayings->addNugget($category, "Anyone can find the switch after the lights are on.");
$Sayings->addNugget($category, "When you see a good person, think of becoming like her or him. When you see someone not so good, reflect on your own weak points.");
$Sayings->addNugget($category, "I slept and dreamt life is beauty, I woke and found life is duty.");
$Sayings->addNugget($category, "They must often change who would remain constant in happiness and wisdom.");
$Sayings->addNugget($category, "Don't complain about the snow on your neighbor's roof when your own doorstep is unclean.");
$Sayings->addNugget($category, "A lion chased me up a tree, and I greatly enjoyed the view from the top.");
$Sayings->addNugget($category, "Be not ashamed of mistakes and thus make them crimes.");
$Sayings->addNugget($category, "The superior man is modest in his speech, but exceeds in his actions.");
$Sayings->addNugget($category, "Be strict with yourself but least reproachful of others and complaint is kept afar.");
$Sayings->addNugget($category, "Roads were made for journeys not destinations.");
$Sayings->addNugget($category, "No matter how busy you may think you are you must find time for reading, or surrender yourself to self-chosen ignorance.");
$Sayings->addNugget($category, "Think of tomorrow, the past can't be mended.");
$Sayings->addNugget($category, "Respect yourself and others will respect you.");
$Sayings->addNugget($category, "To be wronged is nothing, unless you continue to remember it.");
$Sayings->addNugget($category, "I hear and I forget. I see and I remember. I do and I understand.");
$Sayings->addNugget($category, "By nature, men are nearly alike; by practice, they get to be wide apart.");
$Sayings->addNugget($category, "Learn as if you were not reaching your goal and as though you were scared of missing it.");
$Sayings->addNugget($category, "Never contract friendship with a man that is not better than thyself.");
$Sayings->addNugget($category, "He who knows all the answers has not been asked all the questions.");
$Sayings->addNugget($category, "Those who cannot forgive others break the bridge over which they themselves must pass.");
$Sayings->addNugget($category, "Those who know the truth are not equal to those who love it.");
$Sayings->addNugget($category, "The superior man thinks always of virtue; the common man thinks of comfort.");
$Sayings->addNugget($category, "The superior man acts before he speaks, and afterwards speaks according to his action.");
$Sayings->addNugget($category, "Success depends upon previous preparation, and without such preparation there is sure to be failure.");
$Sayings->addNugget($category, "Only the wisest and stupidest of men never change.");
$Sayings->addNugget($category, "Study the past if you would define the future.");
$Sayings->addNugget($category, "Our greatest glory is not in never falling, but in rising every time we fall.");
$Sayings->addNugget($category, "Learning without thought is labor lost; thought without learning is perilous.");
$Sayings->addNugget($category, "Do not impose on others what you yourself do not desire.");
$Sayings->addNugget($category, "The superior man makes the difficulty to be overcome his first interest; success only comes later.");
$Sayings->addNugget($category, "If you make a mistake and do not correct it, this is called a mistake.");
$Sayings->addNugget($category, "Education breeds confidence. Confidence breeds hope. Hope breeds peace.");
$Sayings->addNugget($category, "A superior man is modest in his speech, but exceeds in his actions.");
$Sayings->addNugget($category, "To see the right and not to do it is cowardice.");
$Sayings->addNugget($category, "Virtuous people often revenge themselves for the constraints to which they submit by the boredom which they inspire.");
$Sayings->addNugget($category, "He who acts with a constant view to his own advantage will be much murmured against.");
$Sayings->addNugget($category, "The superior man is distressed by the limitations of his ability; he is not distressed by the fact that men do not recognize the ability that he has.");
$Sayings->addNugget($category, "To see what is right and not to do it is want of courage, or of principle.");
$Sayings->addNugget($category, "When anger rises, think of the consequences.");
$Sayings->addNugget($category, "To know what you know and what you do not know, that is true knowledge.");
$Sayings->addNugget($category, "I want you to be everything that's you, deep at the center of your being.");
$Sayings->addNugget($category, "The object of the superior man is truth.");
$Sayings->addNugget($category, "When you have faults, do not fear to abandon them.");
$Sayings->addNugget($category, "To go beyond is as wrong as to fall short.");
$Sayings->addNugget($category, "If you think in terms of a year, plant a seed; if in terms of ten years, plant trees; if in terms of one hundred years, teach the people.");
$Sayings->addNugget($category, "If you look into your own heart, and you find nothing wrong there, what is there to worry about? What is there to fear?");
$Sayings->addNugget($category, "It does not matter how slowly you go as long as you do not stop.");
$Sayings->addNugget($category, "Virtue is not left to stand alone. He who practices it will have neighbors.");
$Sayings->addNugget($category, "Better a diamond with a flaw than a pebble without.");
$Sayings->addNugget($category, "The superior man does not, even for the space of a single meal, act contrary to virtue. In moments of haste, he cleaves to it. In seasons of danger, he cleaves to it.");
$Sayings->addNugget($category, "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.");
$Sayings->addNugget($category, "Go before the people with your example, and be laborious in their affairs.");
$Sayings->addNugget($category, "When we see persons of worth, we should think of equaling them; when we see persons of a contrary character, we should turn inwards and examine ourselves.");
$Sayings->addNugget($category, "If we don't know life, how can we know death?");
$Sayings->addNugget($category, "The expectations of life depend upon diligence; the mechanic that would perfect his work must first sharpen his tools.");
$Sayings->addNugget($category, "He who speaks without modesty will find it difficult to make his words good.");
$Sayings->addNugget($category, "What you do not want done to yourself, do not do to others.");
$Sayings->addNugget($category, "Without feelings of respect, what is there to distinguish men from beasts?");
$Sayings->addNugget($category, "You cannot open a book without learning something.");
$Sayings->addNugget($category, "A gentleman would be ashamed should his deeds not match his words.");
$Sayings->addNugget($category, "When a person should be spoken with, and you don't speak with them, you lose them. When a person shouldn't be spoken with and you speak to them, you waste your breath. The wise do not lose people, nor do they waste their breath.");
$Sayings->addNugget($category, "To see and listen to the wicked is already the beginning of wickedness.");
$Sayings->addNugget($category, "Wherever you go, go with all your heart.");
$Sayings->addNugget($category, "Give a bowl of rice to a man and you will feed him for a day. Teach him how to grow his own rice and you will save his life.");
$Sayings->addNugget($category, "Study the past, if you would divine the future.");
$Sayings->addNugget($category, "It is more shameful to distrust our friends than to be deceived by them.");
$Sayings->addNugget($category, "Life is really simple, but we insist on making it complicated.");
$Sayings->addNugget($category, "Silence is a true friend who never betrays.");
$Sayings->addNugget($category, "By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.");
$Sayings->addNugget($category, "Wisdom, compassion, and courage are the three universally recognized moral qualities of men.");
$Sayings->addNugget($category, "Death and life have their determined appointments; riches and honors depend upon heaven.");
$Sayings->addNugget($category, "Everything has beauty, but not everyone sees it.");
$Sayings->addNugget($category, "The more man meditates upon good thoughts, the better will be his world and the world at large.");
$Sayings->addNugget($category, "He who learns but does not think, is lost! He who thinks but does not learn is in great danger.");
$Sayings->addNugget($category, "If you don't want to do something, don't impose on others.");
$Sayings->addNugget($category, "It is easy to hate and it is difficult to love. This is how the whole scheme of things works. All good things are difficult to achieve; and bad things are very easy to get.");
$Sayings->addNugget($category, "The strength of a nation derives from the integrity of the home.");
$Sayings->addNugget($category, "The superior man understands what is right; the inferior man understands what will sell.");
$Sayings->addNugget($category, "Never give a sword to a man who can't dance.");
$Sayings->addNugget($category, "We should feel sorrow, but not sink under its oppression.");
$Sayings->addNugget($category, "Imagination is more important than knowledge.");
$Sayings->addNugget($category, "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it – this is knowledge.");

$Wisdom->addChunk($Sayings);
