<?php
$Sutras = new Chunk("sutras","Yoga Sutras","https://www.amazon.com/dp/B008CBDJ7U");

$category = "1 Samadhi Pada";
$Sutras->addNugget($category, "1 With prayers for divine blessings, now begins an exposition of the sacred art of yoga.");
$Sutras->addNugget($category, "2 Yoga is the cessation of movements in the consciousness.");
$Sutras->addNugget($category, "3 Then, the seer dwells in his own true splendour.");
$Sutras->addNugget($category, "4 At other times, the seer identifies with the fluctuating consciousness.");
$Sutras->addNugget($category, "5 The movements of consciousness are fivefold. They may be cognizable or non-cognizable, painful or non-painful.");
$Sutras->addNugget($category, "6 They are caused by correct knowledge, illusion, delusion, sleep and memory.");
$Sutras->addNugget($category, "7 Correct knowledge is direct, inferred or proven as factual.");
$Sutras->addNugget($category, "8 Illusory or erroneous knowledge is based on non-fact or the non-real.");
$Sutras->addNugget($category, "9 Verbal knowledge devoid of substance is fancy or imagination.");
$Sutras->addNugget($category, "10 Sleep is the non-deliberate absence of thought-waves or knowledge.");
$Sutras->addNugget($category, "11 Memory is the unmodified recollection of words and experiences.");
$Sutras->addNugget($category, "12 Practice and detachment are the means to still the movements of consciousness.");
$Sutras->addNugget($category, "13 Practice is the steadfast effort to still these fluctuations.");
$Sutras->addNugget($category, "14 Long, uninterrupted, alert practice is the firm foundation for restraining the fluctuations.");
$Sutras->addNugget($category, "15 Renunciation is the practice of detachment from desires.");
$Sutras->addNugget($category, "16 The ultimate renunciation is when one transcends the qualities of nature and perceives the soul.");
$Sutras->addNugget($category, "17 Practice and detachment develop four types of samadhi: self-analysis, synthesis, bliss, and the experience of pure being.");
$Sutras->addNugget($category, "18 The void arising in these experiences is another samadhi. Hidden impressions lie dormant, but spring up during moments of awareness, creating fluctuations and disturbing the purity of the consciousness.");
$Sutras->addNugget($category, "19 In this state, one may experience bodilessness, or become merged in nature. This may lead to isolation or to a state of loneliness.");
$Sutras->addNugget($category, "20 Practice must be pursued with trust, confidence, vigour, keen memory and power of absorption to break this spiritual complacency.");
$Sutras->addNugget($category, "21 The goal is near for those who are supremely vigorous and intense in practice.");
$Sutras->addNugget($category, "22 There are differences between those who are mild, average and keen in their practices.");
$Sutras->addNugget($category, "23 Or, the citta may be restrained by profound meditation upon God and total surrender to Him.");
$Sutras->addNugget($category, "24 God is the Supreme Being, totally free from conflicts, unaffected by actions and untouched by cause and effect.");
$Sutras->addNugget($category, "25 God is the unexcelled seed of all knowledge.");
$Sutras->addNugget($category, "26 God is the first, foremost and absolute guru, unconditioned by time.");
$Sutras->addNugget($category, "27 He is represented by the sacred syllable Aum, called pranava.");
$Sutras->addNugget($category, "28 The mantra AUM is to be repeated constantly, with feeling, realizing its full significance.");
$Sutras->addNugget($category, "29 Meditation on God with the repetition of AUM removes obstacles to the mastery of the inner self.");
$Sutras->addNugget($category, "30 These obstacles are disease, inertia, doubt, heedlessness, laziness, indiscipline of the senses, erroneous views, lack of perseverance, and backsliding.");
$Sutras->addNugget($category, "31 Sorrow, despair, unsteadiness of the body and irregular breathing further distract the citta.");
$Sutras->addNugget($category, "32 Adherence to single-minded effort prevents these impediments.");
$Sutras->addNugget($category, "33 Through cultivation of friendliness, compassion, joy, and indifference to pleasure and pain, virtue and vice respectively, the consciousness becomes favourably disposed, serene and benevolent.");
$Sutras->addNugget($category, "34 Or, by maintaining the pensive state felt at the time of soft and steady exhalation and during passive retention after exhalation.");
$Sutras->addNugget($category, "35 Or, by contemplating an object that helps to maintain steadiness of mind and consciousness.");
$Sutras->addNugget($category, "36 Or, inner stability is gained by contemplating a luminous, sorrowless, effulgent light.");
$Sutras->addNugget($category, "37 Or, by contemplating on enlightened sages who are free from desires and attachments, calm and tranquil, or by contemplating divine objects.");
$Sutras->addNugget($category, "38 Or, by recollecting and contemplating the experiences of dream-filled or dreamless sleep during a watchful, waking state.");
$Sutras->addNugget($category, "39 Or, by meditating on any desired object conducive to steadiness of consciousness.");
$Sutras->addNugget($category, "40 Mastery of contemplation brings the power to extend from the finest particle to the greatest.");
$Sutras->addNugget($category, "41 The yogi realizes that the knower, the instrument of knowing and the known are one, himself, the seer. Like a pure transparent jewel, he reflects an unsullied purity.");
$Sutras->addNugget($category, "42 At this stage, called savitarka samapatti, the word, meaning and content are blended, and become special knowledge.");
$Sutras->addNugget($category, "43 In nirvitarka samapatti, the difference between memory and intellectual illumination is disclosed; memory is cleansed and consciousness shines without reflection.");
$Sutras->addNugget($category, "44 The contemplation of subtle aspects is similarly explained as deliberate (savicara samapatti) or non-deliberate (nirvicara samapatti).");
$Sutras->addNugget($category, "45 The subtlest level of nature (prakrti) is consciousness. When consciousness dissolves in nature, it loses all marks and becomes pure.");
$Sutras->addNugget($category, "46 The states of samadhi described in the previous sutras are dependent upon a support or seed, and are termed sabija.");
$Sutras->addNugget($category, "47 From proficiency in nirvicara samapatti comes purity. Sattva or luminosity flows undisturbed, kindling the spiritual light of the self.");
$Sutras->addNugget($category, "48 When consciousness dwells in wisdom, a truth-bearing state of direct spiritual perception dawns.");
$Sutras->addNugget($category, "49 This truth-bearing knowledge and wisdom is distinct from and beyond the knowledge gleaned from books, testimony, or inference.");
$Sutras->addNugget($category, "50 A new life begins with this truth-bearing light. Previous impressions are left behind and new ones are prevented.");
$Sutras->addNugget($category, "51 When that new light of wisdom is also relinquished, seedless samadhi dawns.");

$category = "2 Sadhana Pada";
$Sutras->addNugget($category, "1 Burning zeal in practice, self-study and study of scriptures, and surrender to God are the acts of yoga.");
$Sutras->addNugget($category, "2 The practice of yoga reduces afflictions and leads to samadhi.");
$Sutras->addNugget($category, "3 The five afflictions which disturb the equilibrium of consciousness are: ignorance or lack of wisdom, ego, pride of the ego or the sense of ‘I’, attachment to pleasure, aversion to pain, fear of death and clinging to life.");
$Sutras->addNugget($category, "4 Lack of true knowledge is the source of all pains and sorrows whether dormant, attenuated, interrupted or fully active.");
$Sutras->addNugget($category, "5 Mistaking the transient for the permament, the impure for the pure, pain for pleasure, and that which is not the self for the self: all this is called lack of spiritual knowledge, avidya.");
$Sutras->addNugget($category, "6 Egoism is the identification of the seer with the instrumental power of seeing.");
$Sutras->addNugget($category, "7 Pleasure leads to desire and emotional attachment.");
$Sutras->addNugget($category, "8 Unhappiness leads to hatred.");
$Sutras->addNugget($category, "9 Self-preservation or attachment to life is the subtlest of all afflictions. It is found even in wise men.");
$Sutras->addNugget($category, "10 Subtle afflictions are to be minimized and eradicated by a process of involution.");
$Sutras->addNugget($category, "11 The fluctuations of consciousness created by gross and subtle afflictions are to be silenced through meditation.");
$Sutras->addNugget($category, "12 The accumulated imprints of past lives, rooted in afflictions, will be experienced in present and future lives.");
$Sutras->addNugget($category, "13 As long as the root of actions exists, it will give rise to class of birth, span of life and experiences.");
$Sutras->addNugget($category, "14 According to our good, bad or mixed actions, the quality of our life, its span, and the nature of birth are experienced as being pleasant or painful.");
$Sutras->addNugget($category, "15 The wise man knows that owing to fluctuations, the qualities of nature, and subliminal impressions, even pleasant experiences are tinged with sorrow, and he keeps aloof from them.");
$Sutras->addNugget($category, "16 The pains which are yet to come can be and are to be avoided.");
$Sutras->addNugget($category, "17 The cause of pain is the association or identification of the seer (atma) with the seen (prakrti) and the remedy lies in their dissociation.");
$Sutras->addNugget($category, "18 Nature, its three qualities, sattva, rajas and tamas, and its evolutes, the elements, mind, senses of perception and organs of action, exist eternally to serve the seer, for enjoyment or emancipation.");
$Sutras->addNugget($category, "19 The gunas generate their characteristic divisions and energies in the seer. Their stages are distinguishable and non-distinguishable, differentiable and non-differentiable.");
$Sutras->addNugget($category, "20 The seer is pure consciousness. He witnesses nature without being reliant on it.");
$Sutras->addNugget($category, "21 Nature and intelligence exist solely to serve the seer’s true purpose, emancipation.");
$Sutras->addNugget($category, "22 The relationship with nature ceases for emancipated beings, its purpose having been fulfilled, but its processes continue to affect others.");
$Sutras->addNugget($category, "23 The conjunction of the seer with the seen is for the seer to discover his own true nature.");
$Sutras->addNugget($category, "24 Lack of spiritual understanding (avidya) is the cause of the false identification of the seer with the seen.");
$Sutras->addNugget($category, "25 The destruction of ignorance through right knowledge breaks the link binding the seer to the seen. This is kaivalya, emancipation.");
$Sutras->addNugget($category, "26 The ceaseless flow of discriminative knowledge in thought, word and deed destroys ignorance, the source of pain.");
$Sutras->addNugget($category, "27 Through this unbroken flow of discriminative awareness, one gains perfect knowledge which has seven spheres.");
$Sutras->addNugget($category, "28 By dedicated practice of the various aspects of yoga impurities are destroyed: the crown of wisdom radiates in glory.");
$Sutras->addNugget($category, "29 Moral injunctions (yama), fixed observances (niyama), posture (Asana), regulation of breath (pranayama), internalization of the senses towards their source (pratyahara), concentration (dharana), meditation (dhyana) and absorption of consciousness in the self (samadhi), are the eight constituents of yoga.");
$Sutras->addNugget($category, "30 Non-violence, truth, abstention from stealing, continence, and absence of greed for possessions beyond one’s need are the five pillars of yama.");
$Sutras->addNugget($category, "31 Yamas are the great, mighty, universal vows, unconditioned by place, time and class.");
$Sutras->addNugget($category, "32 Cleanliness, contentment, religious zeal, self-study and surrender of the self to the supreme Self or God are the niyamas.");
$Sutras->addNugget($category, "33 Principles which run contrary to yama and niyama are to be countered with the knowledge of discrimination.");
$Sutras->addNugget($category, "34 Uncertain knowledge giving rise to violence, whether done directly or indirectly, or condoned, is caused by greed, anger or delusion in mild, moderate or intense degree. It results in endless pain and ignorance. Through introspection comes the end of pain and ignorance.");
$Sutras->addNugget($category, "35 When non-violence in speech, thought and action is established, one’s aggressive nature is relinquished and others abandon hostility in one’s presence.");
$Sutras->addNugget($category, "36 When the sadhaka is firmly established in the practice of truth, his words become so potent that whatever he says comes to realization.");
$Sutras->addNugget($category, "37 When abstention from stealing is firmly established, precious jewels come.");
$Sutras->addNugget($category, "38 When the sadhaka is firmly established in continence, knowledge, vigour, valour and energy flow to him.");
$Sutras->addNugget($category, "39 Knowledge of past and future lives unfolds when one is free from greed for possessions.");
$Sutras->addNugget($category, "40 Cleanliness of body and mind develops disinterest in contact with others for self-gratification.");
$Sutras->addNugget($category, "41 When the body is cleansed, the mind purified and the senses controlled, joyful awareness needed to realize the inner self, also comes.");
$Sutras->addNugget($category, "42 From contentment and benevolence of consciousness comes supreme happiness.");
$Sutras->addNugget($category, "43 Self-discipline (tapas) burns away impurities and kindles the sparks of divinity.");
$Sutras->addNugget($category, "44 Self-study leads towards the realization of God or communion with one’s desired deity.");
$Sutras->addNugget($category, "45 Surrender to God brings perfection in samadhi.");
$Sutras->addNugget($category, "46 Asana is perfect firmness of body, steadiness of intelligence and benevolence of spirit.");
$Sutras->addNugget($category, "47 Perfection in an Asana is achieved when the effort to perform it becomes effortless and the infinite being within is reached.");
$Sutras->addNugget($category, "48 From then on, the sadhaka is undisturbed by dualities.");
$Sutras->addNugget($category, "49 Pranayama is the regulation of the incoming and outgoing flow of breath with retention. It is to be practised only after perfection in Asana is attained.");
$Sutras->addNugget($category, "50 Pranayama has three movements: prolonged and fine inhalation, exhalation and retention; all regulated with precision according to duration and place.");
$Sutras->addNugget($category, "51 The fourth type of pranayama transcends the external and internal pranayamas, and appears effortless and non-deliberate.");
$Sutras->addNugget($category, "52 Pranayama removes the veil covering the light of knowledge and heralds the dawn of wisdom.");
$Sutras->addNugget($category, "53 The mind also becomes fit for concentration.");
$Sutras->addNugget($category, "54 Withdrawing the senses, mind and consciousness from contact with external objects, and then drawing them inwards towards the seer, is pratyahara.");
$Sutras->addNugget($category, "55 Pratyahara results in the absolute control of the sense organs.");

$category = "3 Vibhuti Pada";
$Sutras->addNugget($category, "1 Fixing the consciousness on one point or region is concentration (dharana).");
$Sutras->addNugget($category, "2 A steady, continuous flow of attention directed towards the same point or region is meditation (dhyana).");
$Sutras->addNugget($category, "3 When the object of meditation engulfs the meditator, appearing as the subject, self-awareness is lost. This is samadhi.");
$Sutras->addNugget($category, "4 These three together – dharana, dhyana and samadhi – constitute integration or samyama.");
$Sutras->addNugget($category, "5 From mastery of samyama comes the light of awareness and insight.");
$Sutras->addNugget($category, "6 Samyama may be applied in various spheres to derive its usefulness.");
$Sutras->addNugget($category, "7 These three aspects of yoga are internal, compared to the former five.");
$Sutras->addNugget($category, "8 Similarly, samyama is external when compared to seedless (nirbija) samadhi.");
$Sutras->addNugget($category, "9 Study of the silent moments between rising and restraining subliminal impressions is the transformation of consciousness towards restraint (nirodhaparinamah).");
$Sutras->addNugget($category, "10 The restraint of rising impressions brings about an undisturbed flow of tranquillity.");
$Sutras->addNugget($category, "11 The weakening of scattered attention and the rise of one-pointed attention in the citta is the transformation towards samadhi.");
$Sutras->addNugget($category, "12 When rising and falling thought processes are in balance, one-pointed consciousness emerges. Maintenance of awareness with keen intensity from one-pointed attention to no-pointed attentiveness is ekagrata parinama.");
$Sutras->addNugget($category, "13 Through these three phases, cultured consciousness is transformed from its potential state (dharma) towards further refinement (laksana) and the zenith of refinement (avastha). In this way, the transformation of elements, senses and mind takes place.");
$Sutras->addNugget($category, "14 The substrata is that which continues to exist and maintain its characteristic quality in all states, whether manifest, latent, or subdued.");
$Sutras->addNugget($category, "15 Successive sequential changes cause the distinctive changes in the consciousness.");
$Sutras->addNugget($category, "16 By mastery of the three transformations of nature (dharma), quality (laksana) and condition (avastha), through samyama on the nirodha, samadhi, and ekagrata states of consciousness, the yogi acquires knowledge of the past and the future.");
$Sutras->addNugget($category, "17 Words, objects and ideas are superimposed, creating confusion; by samyama, one gains knowledge of the language of all beings.");
$Sutras->addNugget($category, "18 Through direct perception of his subliminal impressions, the yogi gains knowledge of his previous lives.");
$Sutras->addNugget($category, "19 He acquires the ability to understand the minds of others.");
$Sutras->addNugget($category, "20 A yogi who is able to read the minds of others in general, can also, if necessary, precisely identify specific contents which are beyond the reach of the mind.");
$Sutras->addNugget($category, "21 By control over the subtle body, the yogi can suspend at will the rays of light emanating from himself so that he becomes invisible to onlookers. He may again make himself visible by bringing back the power of perceptibility.");
$Sutras->addNugget($category, "22 In the same way as described above, he is able to arrest sound, smell, taste, form and touch.");
$Sutras->addNugget($category, "23 The effects of action are immediate or delayed. By samyama on his actions, a yogi will gain foreknowledge of their final fruits. He will know the exact time of his death by omens.");
$Sutras->addNugget($category, "24 He gains moral and emotional strength by perfecting friendliness and other virtues towards one and all.");
$Sutras->addNugget($category, "25 By samyama on strength, the yogi will develop the physical strength, grace, and endurance of an elephant.");
$Sutras->addNugget($category, "26 Concealed things, near or far, are revealed to a yogi.");
$Sutras->addNugget($category, "27 By samyama on the sun the yogi will have knowledge of the seven worlds, and of the seven cosmic centres in the body.");
$Sutras->addNugget($category, "28 By samyama on the moon, the yogi will know the position and system of the stars.");
$Sutras->addNugget($category, "29 By samhyama on the Pole Star, the yogi knows the course of destiny.");
$Sutras->addNugget($category, "30 By samyama on the navel, the yogi acquires perfect knowledge of the disposition of the human body.");
$Sutras->addNugget($category, "31 By samyama on the pit of the throat, the yogi overcomes hunger and thirst.");
$Sutras->addNugget($category, "32 By samyama on kurmanani, at the pit of the throat, the yogi can make his body and mind firm and immobile like a tortoise.");
$Sutras->addNugget($category, "33 By performing samyama on the light of the crown of the head (ajña cakra), the yogi has visions of perfected beings.");
$Sutras->addNugget($category, "34 Through the faculty of spiritual perception the yogi becomes the knower of all knowledge.");
$Sutras->addNugget($category, "35 By samyama on the region of the heart, the yogi acquires a thorough knowledge of the contents and tendencies of consciousness.");
$Sutras->addNugget($category, "36 By samyama, the yogi easily differentiates between the intelligence and the soul which is real and true.");
$Sutras->addNugget($category, "37 Through that spiritual perception, the yogi acquires the divine faculties of hearing, touch, vision, taste and smell. He can even generate these divine emanations by his own will.");
$Sutras->addNugget($category, "38 These attainments are impediments to samadhi, although they are powers in active life.");
$Sutras->addNugget($category, "39 Through relaxation of the causes of bondage, and the free flow of consciousness, the yogi enters another’s body at will.");
$Sutras->addNugget($category, "40 By mastery of udana vayu, the yogi can walk over water, swamps and thorns without touching them. He can also levitate.");
$Sutras->addNugget($category, "41 By samyama on samana vayu, a yogi glows like fire and his aura shines.");
$Sutras->addNugget($category, "42 By samyama on the relation between space and sound, the yogi acquires the power of hearing distant and divine sounds. The organ of hearing, the ear, grasps sound in space. This is the conquest of air.");
$Sutras->addNugget($category, "43 By knowing the relationship between the body and ether, the yogi transforms his body and mind so that they become as light as cotton fibre. He can then levitate in space. This is the conquest of ether.");
$Sutras->addNugget($category, "44 By samyama on mahavideha (the disembodied state), where consciousness acts outside the body, the veil covering the light of illumination is destroyed.");
$Sutras->addNugget($category, "45 By samyama on the elements – their mass, forms, subtlety, conjunction and purposes, the yogi becomes Lord over them all.");
$Sutras->addNugget($category, "46 From that arises perfection of the body, the ability to resist the play of the elements, and powers such as minuteness.");
$Sutras->addNugget($category, "47 Perfection of the body consists of beauty of form, grace, strength, compactness, and the hardness and brilliance of a diamond.");
$Sutras->addNugget($category, "48 Through samyama upon the purpose of the conjunction of the process of knowing, the ego, and nature, there is mastery over the senses.");
$Sutras->addNugget($category, "49 By mastery over the senses of perception, the yogi’s speed of body, senses and mind matches that of the soul, independent of the primary causes of nature. Unaided by consciousness, he subdues the first principle of nature (mahat).");
$Sutras->addNugget($category, "50 Only one who knows the difference between the illuminative intelligence and the seer attains supreme knowledge of all that exists and all that manifests.");
$Sutras->addNugget($category, "51 By destruction of the seeds of bondage and the renunciation of even these powers, comes eternal emancipation.");
$Sutras->addNugget($category, "52 When approached by celestial beings, there should be neither attachment nor surprise, for undesirable connections can occur again.");
$Sutras->addNugget($category, "53 By samyama on moment and on the continuous flow of moments, the yogi gains exalted knowledge, free from the limitations of time and space.");
$Sutras->addNugget($category, "54 By this knowledge the yogi is able to distinguish unerringly the differences in similar objects which cannot be distinguished by rank, qualitative signs or position in space.");
$Sutras->addNugget($category, "55 The essential characteristic of the yogi’s exalted knowledge is that he grasps instantly, clearly and wholly, the aims of all objects without going into the sequence of time or change.");
$Sutras->addNugget($category, "56 When the purity of intelligence equals the purity of the soul, the yogi has reached kaivalya, perfection in yoga.");

$category = "4 Kaivalya Pada";
$Sutras->addNugget($category, "1 Accomplishments may be attained through birth, the use of herbs, incantations, self-discipline or samadhi.");
$Sutras->addNugget($category, "2 The abundant flow of nature’s energy brings about a transformation in one’s birth, aiding the process of evolution.");
$Sutras->addNugget($category, "3 Nature’s efficient cause does not impel its potentialities into action, but helps to remove the obstacles to evolution, just as a farmer builds banks to irrigate his fields.");
$Sutras->addNugget($category, "4 Constructed or created mind springs from the sense of individuality (asmita).");
$Sutras->addNugget($category, "5 Consciousness is one, but it branches into many different types of activities and innumerable thought-waves.");
$Sutras->addNugget($category, "6 Of these activities of consciousness of perfected beings, only those which proceed from meditation are free from latent impressions and influences.");
$Sutras->addNugget($category, "7 A yogi’s actions are neither white nor black. The actions of others are of three kinds, white, black or grey.");
$Sutras->addNugget($category, "8 These three types of actions leave impressions which become manifest when conditions are favourable and ripe.");
$Sutras->addNugget($category, "9 Life is a continuous process, even though it is demarcated by race, place and time. Due to the uninterrupted close relationship between memory and subliminal impressions, the fruits of actions remain intact from one life to the next, as if there were no separation between births.");
$Sutras->addNugget($category, "10 These impressions, memories and desires have existed eternally, as the desire to live is eternal.");
$Sutras->addNugget($category, "11 Impressions and desires are bound together by their dependence upon cause and effect. In the absence of the latter, the former too ceases to function.");
$Sutras->addNugget($category, "12 The existence of the past and the future is as real as that of the present. As moments roll into movements which have yet to appear as the future, the quality of knowledge in one’s intellect and consciousness is affected.");
$Sutras->addNugget($category, "13 The three phases of time intermingle rhythmically and interweave with the qualities of nature. They change the composition of nature’s properties into gross and subtle.");
$Sutras->addNugget($category, "14 Unity in the mutation of time caused by the abiding qualities of nature, sattva, rajas and tamas, causes modifications in objects, but their unique essence, or reality, does not change.");
$Sutras->addNugget($category, "15 Due to the variance in the quality of mind-content, each person may view the same object differently, according to his own way of thinking.");
$Sutras->addNugget($category, "16 An object exists independent of its cognizance by any one consciousness. What happens to it when that consciousness is not there to perceive it?");
$Sutras->addNugget($category, "17 An object remains known or unknown according to the conditioning or expectation of the consciousness.");
$Sutras->addNugget($category, "18 Purusa is ever illuminative and changeless. Being constant and master of the mind, he always knows the moods and modes of consciousness.");
$Sutras->addNugget($category, "19 Consciousness cannot illumine itself as it is a knowable object.");
$Sutras->addNugget($category, "20 Consciousness cannot comprehend both the seer and itself at the same time.");
$Sutras->addNugget($category, "21 If consciousness were manifold in one’s being, each cognizing the other, the intelligence too would be manifold, so the projections of mind would be many, each having its own memory.");
$Sutras->addNugget($category, "22 Consciousness distinguishes its own awareness and intelligence when it reflects and identifies its source – the changeless seer – and assumes his form.");
$Sutras->addNugget($category, "23 Consciousness, reflected by the seer as well as by the seen, appears to be all-comprehending.");
$Sutras->addNugget($category, "24 Though the fabric of consciousness is interwoven with innumerable desires and subconscious impressions, it exists for the seer on account of its proximity to the seer as well as to the objective world.");
$Sutras->addNugget($category, "25 For one who realizes the distinction between citta and atma, the sense of separation between the two disappears.");
$Sutras->addNugget($category, "26 Then consciousness is drawn strongly towards the seer or the soul due to the gravitational force of its exalted intelligence.");
$Sutras->addNugget($category, "27 Notwithstanding this progress, if one is careless during the interval, a fissure arises due to past hidden impressions, creating division between the consciousness and the seer.");
$Sutras->addNugget($category, "28 In the same way as the sadhaka strives to be free from afflictions, the yogi must handle these latent impressions judiciously to extinguish them.");
$Sutras->addNugget($category, "29 The yogi who has no interest even in this highest state of evolution, and maintains supreme attentive, discriminative awareness, attains dharmameghah samadhi: he contemplates the fragrance of virtue and justice.");
$Sutras->addNugget($category, "30 Then comes the end of afflictions and of karma.");
$Sutras->addNugget($category, "31 Then, when the veils of impurities are removed, the highest, subjective, pure, infinite knowledge is attained, and the knowable, the finite, appears as trivial.");
$Sutras->addNugget($category, "32 When dharmameghah samadhi is attained, qualities of nature (gunas) come to rest. Having fulfilled their purpose, their sequence of successive mutations is at an end.");
$Sutras->addNugget($category, "33 As the mutations of the gunas cease to function, time, the uninterrupted movement of moments, stops. This deconstruction of the flow of time is comprehensible only at this final stage of emancipation.");
$Sutras->addNugget($category, "34 Kaivalya, liberation, comes when the yogi has fulfilled the purusarthas, the fourfold aims of life, and has transcended the gunas. Aims and gunas return to their source, and consciousness is established in its own natural purity.");

$Wisdom->addChunk($Sutras);
