<?php

$Thoreau = new Chunk("quotes","Henry David Thoreau Quotes","https://quotes.thefamouspeople.com/henry-david-thoreau-1608.php");

$category = "Henry David Thoreau";

$Thoreau->addNugget($category, "A lake is a landscape's most beautiful and expressive feature. It is earth's eye; looking into which the beholder measures the depth of his own nature.");
$Thoreau->addNugget($category, "A man is rich in proportion to the number of things which he can afford to let alone.");
$Thoreau->addNugget($category, "All good things are wild and free.");
$Thoreau->addNugget($category, "All men want, not something to do with, but something to do, or rather something to be.");
$Thoreau->addNugget($category, "Amid a world of noisy, shallow actors it is noble to stand aside and say, I will simply be.");
$Thoreau->addNugget($category, "An early-morning walk is a blessing for the whole day.");
$Thoreau->addNugget($category, "Any fool can make a rule And any fool will mind it.");
$Thoreau->addNugget($category, "As if you could kill time without injuring eternity.");
$Thoreau->addNugget($category, "As you simplify your life, the laws of the universe will be simpler; solitude will not be solitude, poverty will not be poverty, nor weakness weakness.");
$Thoreau->addNugget($category, "Be yourself - not your idea of what you think somebody else's idea of yourself should be.");
$Thoreau->addNugget($category, "Books are the treasured wealth of the world and the fit inheritance of generations and nations.");
$Thoreau->addNugget($category, "Books must be read as deliberately and reservedly as they were written.");
$Thoreau->addNugget($category, "Could a greater miracle take place than for us to look through each other’s eyes for an instant?");
$Thoreau->addNugget($category, "Disobedience is the true foundation of liberty. The obedient must be slaves.");
$Thoreau->addNugget($category, "Do not be too moral. You may cheat yourself out of much life so. Aim above morality. Be not simply good, be good for something.");
$Thoreau->addNugget($category, "Do not hire a man who does your work for money, but him who does it for love of it.");
$Thoreau->addNugget($category, "Do not lose hold of your dreams or aspirations. For if you do, you may still exist but you have ceased to live.");
$Thoreau->addNugget($category, "Dreams are the touchstones of our characters.");
$Thoreau->addNugget($category, "Every generation laughs at the old fashions, but follows religiously the new.");
$Thoreau->addNugget($category, "Every morning was a cheerful invitation to make my life of equal simplicity, and I may say innocence, with Nature herself.");
$Thoreau->addNugget($category, "Friends... they cherish one another's hopes. They are kind to one another's dreams.");
$Thoreau->addNugget($category, "Go confidently in the direction of your dreams. Live the life you've imagined.");
$Thoreau->addNugget($category, "Heaven is under our feet as well as over our heads.");
$Thoreau->addNugget($category, "How many a man has dated a new era in his life from the reading of a book.");
$Thoreau->addNugget($category, "How vain it is to sit down to write when you have not stood up to live.");
$Thoreau->addNugget($category, "I can alter my life by altering my attitude. He who would have nothing to do with thorns must never attempt to gather flowers.");
$Thoreau->addNugget($category, "I had three chairs in my house; one for solitude, two for friendship, three for society.");
$Thoreau->addNugget($category, "I have a room all to myself; it is nature.");
$Thoreau->addNugget($category, "I have an immense appetite for solitude, like an infant for sleep, and if I don't get enough for this year, I shall cry all the next.");
$Thoreau->addNugget($category, "I have no doubt that it is part of the destiny of the human race in it's gradual improvement, to leave off eating animals.");
$Thoreau->addNugget($category, "I have, as it were, my own sun and moon and stars, and a little world all to myself.");
$Thoreau->addNugget($category, "I make myself rich by making my wants few.");
$Thoreau->addNugget($category, "I say, beware of all enterprises that require new clothes, and not rather a new wearer of clothes.");
$Thoreau->addNugget($category, "I should not talk so much about myself if there were anybody else whom I knew as well.");
$Thoreau->addNugget($category, "I was not designed to be forced. I will breathe after my own fashion. Let us see who is the strongest.");
$Thoreau->addNugget($category, "I went to the woods because I wished to live deliberately...");
$Thoreau->addNugget($category, "I would rather sit on a pumpkin, and have it all to myself, than be crowded on a velvet cushion.");
$Thoreau->addNugget($category, "If a man does not keep pace with his companions, perhaps it is because he hears a different drummer. Let him step to the music he hears, however measured or far away.");
$Thoreau->addNugget($category, "If a plant cannot live according to its nature, it dies; and so a man.");
$Thoreau->addNugget($category, "If I repent of anything, it is very likely to be my good behavior. What demon possessed me that I behaved so well?");
$Thoreau->addNugget($category, "If we will be quiet and ready enough, we shall find compensation in every disappointment.");
$Thoreau->addNugget($category, "If you have built castles in the air, your work need not be lost; that is where they should be. Now put the foundations under them.");
$Thoreau->addNugget($category, "If you would convince a man that he does wrong, do right. But do not care to convince him. Men will believe what they see. Let them see.");
$Thoreau->addNugget($category, "In human intercourse the tragedy begins, not when there is misunderstanding about words, but when silence is not understood.");
$Thoreau->addNugget($category, "It is better to have your head in the clouds, and know where you are... than to breathe the clearer atmosphere below them, and think that you are in paradise.");
$Thoreau->addNugget($category, "It is never too late to give up your prejudices.");
$Thoreau->addNugget($category, "It is not enough to be industrious; so are the ants. What are you industrious about?");
$Thoreau->addNugget($category, "It's not what you look at that matters, it's what you see.");
$Thoreau->addNugget($category, "It's not worth our while to let our imperfections disturb us always.");
$Thoreau->addNugget($category, "Live in each season as it passes; breathe the air, drink the drink, taste the fruit, and resign yourself to the influence of the earth.");
$Thoreau->addNugget($category, "Men are born to succeed, not to fail.");
$Thoreau->addNugget($category, "Men have become the tools of their tools.");
$Thoreau->addNugget($category, "Most men lead lives of quiet desperation and go to the grave with the song still in them.");
$Thoreau->addNugget($category, "My greatest skill in life has been to want but little.");
$Thoreau->addNugget($category, "Never look back unless you are planning to go that way.");
$Thoreau->addNugget($category, "Not till we are completely lost or turned around... do we begin to find ourselves.");
$Thoreau->addNugget($category, "Not till we are lost, in other words not till we have lost the world, do we begin to find ourselves, and realize where we are and the infinite extent of our relations.");
$Thoreau->addNugget($category, "Nothing makes the earth seem so spacious as to have friends at a distance; they make the latitudes and longitudes.");
$Thoreau->addNugget($category, "Only that day dawns to which we are awake. There is more day to dawn. The sun is but a morning star.");
$Thoreau->addNugget($category, "Our life is frittered away by detail. Simplify, simplify.");
$Thoreau->addNugget($category, "Our truest life is when we are in dreams awake.");
$Thoreau->addNugget($category, "Public opinion is a weak tyrant compared with our own private opinion. what a man thinks of himself, that it is which determines, or rather indicates, his fate.");
$Thoreau->addNugget($category, "Pursue some path, however narrow and crooked, in which you can walk with love and reverence.");
$Thoreau->addNugget($category, "Rather than love, than money, than fame, give me truth.");
$Thoreau->addNugget($category, "Read the best books first, or you may not have a chance to read them at all.");
$Thoreau->addNugget($category, "Renew thyself completely each day.");
$Thoreau->addNugget($category, "Say what you have to say, not what you ought. Any truth is better than make-believe.");
$Thoreau->addNugget($category, "Simplicity, simplicity, simplicity! I say, let your affairs be as two or three, and not a hundred or a thousand; instead of a million count half a dozen, and keep your accounts on your thumb nail.");
$Thoreau->addNugget($category, "Success usually comes to those who are too busy to be looking for it.");
$Thoreau->addNugget($category, "Take long walks in stormy weather or through deep snows in the fields and woods, if you would keep your spirits up. Deal with brute nature. Be cold and hungry and weary.");
$Thoreau->addNugget($category, "Thank God men cannot fly, and lay waste the sky as well as the earth.");
$Thoreau->addNugget($category, "That man is the richest whose pleasures are the cheapest.");
$Thoreau->addNugget($category, "The cost of a thing is the amount of what I will call life which is required to be exchanged for it, immediately or in the long run.");
$Thoreau->addNugget($category, "The greatest compliment that was ever paid me was when one asked me what I thought, and attended to my answer.");
$Thoreau->addNugget($category, "The heart is forever inexperienced.");
$Thoreau->addNugget($category, "The language of friendship is not words, but meanings.");
$Thoreau->addNugget($category, "The mass of men lead lives of quiet desperation.");
$Thoreau->addNugget($category, "The most I can do for my friend is simply to be his friend.");
$Thoreau->addNugget($category, "The path of least resistance leads to crooked rivers and crooked men.");
$Thoreau->addNugget($category, "The question is not what you look at, but what you see.");
$Thoreau->addNugget($category, "The universe is wider than our views of it.");
$Thoreau->addNugget($category, "There are a thousand hacking at the branches of evil to one who is striking at the root.");
$Thoreau->addNugget($category, "There is no remedy for love, but to love more.");
$Thoreau->addNugget($category, "Things do not change; we change.");
$Thoreau->addNugget($category, "This world is but a canvas for our imagination.");
$Thoreau->addNugget($category, "To be a philosopher is not merely to have subtle thoughts, nor even to found a school, but so to love wisdom as to live according to its dictates, a life of simplicity, independence, magnanimity and trust.");
$Thoreau->addNugget($category, "To be awake is to be completely alive. I have never yet met a man who was quite awake.");
$Thoreau->addNugget($category, "We are born as innocents. We are polluted by advice.");
$Thoreau->addNugget($category, "We are constantly invited to be who we are.");
$Thoreau->addNugget($category, "What does education often do? It makes a straight-cut ditch of a free, meandering brook.");
$Thoreau->addNugget($category, "What lies behind us and what lies ahead of us are tiny matters compared to what lives within us.");
$Thoreau->addNugget($category, "What sort of philosophers are we, who know absolutely nothing of the origin and destiny of cats?");
$Thoreau->addNugget($category, "What's the use of a fine house if you haven't got a tolerable planet to put it on?");
$Thoreau->addNugget($category, "When I hear music, I fear no danger. I am invulnerable. I see no foe. I am related to the earliest times, and to the latest.");
$Thoreau->addNugget($category, "When we are unhurried and wise, we perceive that only great and worthy things have any permanent and absolute existence, that petty fears and petty pleasures are but the shadow of the reality.");
$Thoreau->addNugget($category, "Wildness is the preservation of the world.");
$Thoreau->addNugget($category, "Write while the heat is in you. The writer who postpones the recording of his thoughts uses an iron which has cooled to burn a hole with. He cannot inflame the minds of his audience.");
$Thoreau->addNugget($category, "You cannot dream yourself into a character: you must hammer and forge yourself into one.");
$Thoreau->addNugget($category, "You must live in the present, launch yourself on every wave, find your eternity in each moment.");

$Wisdom->addChunk($Thoreau);
